on:
jobs:
  security-scans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Linting with Flake8
        run: |
          pip install flake8
          flake8 .
          
      - name: SAST Scan (Bandit)
        run: |
          pip install bandit
          # Ignoring 0.0.0.0 warnings as per rules
          bandit -r . --skip B104 
          
      - name: Build Docker Image for scanning
        run: docker build -t test-app .
        
      - name: Container Vulnerability Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-app'
          format: 'table'
          exit-code: '1' # Fails the pipeline if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  push:
    branches:
      - main
  pull_request:
